import type { Metadata } from "next";
import { Geist_Mono, Instrument_Serif, Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const cabinetGrotesk = localFont({
  src: [
    {
      path: "../../assets/fonts/CabinetGrotesk/CabinetGrotesk-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/fonts/CabinetGrotesk/CabinetGrotesk-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../assets/fonts/CabinetGrotesk/CabinetGrotesk-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-cabinet-grotesk",
});

const poppins = localFont({
  src: [
    {
      path: "../../assets/fonts/Poppins/Poppins-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Poppins/Poppins-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Poppins/Poppins-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  style: "italic",
  weight: "400",
  variable: "--font-instrument-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", cabinetGrotesk.variable, poppins.variable, geistMono.variable, instrumentSerif.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
